//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GubaidullinLanguage.Data
{
    using System;
    using System.Linq;
    using System.Collections.Generic;

    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.ClientService = new HashSet<ClientService>();
            this.Tag = new HashSet<Tag>();
        }

        public int ID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Patronymic { get; set; }
        public string GenderCode { get; set; }
        public string Phone { get; set; }
        public string PhotoPath { get; set; }
        public System.DateTime Birthday { get; set; }
        public string Email { get; set; }
        public System.DateTime RegistrationDate { get; set; }

        public string ShortRegistrationDate => RegistrationDate.ToShortDateString();
        public string ShortBirthday => Birthday.ToShortDateString();
        public int VisitCount => Convert.ToInt32(GubaidullinLanguageEntities.GetContext().ClientService.Where(x => x.ClientID == this.ID).Count());

        public string GenderN
        {
            get
            {
                return Gender.Name;
            }
        }
        public string last_start
        {
            get
            {
                return this.ClientService.Max(p => p.StartTime).ToString();
            }
        }
        public string last_startt
        {
            get
            {
                return this.ClientService.Max(p => p.StartTime).ToString();
            }
        }
        public int countStartDates
        {
            get
            {
                return this.ClientService.Count;
            }
        }
        public string start
        {
            get
            {
                return this.ClientService.Select(p => p.StartTime).ToString();
            }
        }
        public string phone
        {
            get
            {
                return Phone.Replace("(", "").Replace(")", "").Replace("-", "");
            }
        }
        public string LastVisitDate
        {
            get
            {
                if (VisitCount == 0)
                    return "нет";
                else
                    return GubaidullinLanguageEntities.GetContext().ClientService.Where(x => x.ClientID == this.ID).Max(p => p.StartTime).ToString();
            }
        }

        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientService> ClientService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tag> Tag { get; set; }
        
    }
}
